### ISSUE TITLE
Set a value, then reset causes error and disable the input

### ISSUE THREAD

**Issue by lucasdidur** [jifalops/datetime_picker_formfield#42]
![](https://i.imgur.com/68yU0jb.png)

```
W/IInputConnectionWrapper( 7958): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper( 7958): getTextBeforeCursor on inactive InputConnection
I/flutter ( 7958): ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
I/flutter ( 7958): The following assertion was thrown while handling a gesture:
I/flutter ( 7958): invalid text selection: TextSelection(baseOffset: 16, extentOffset: 16, affinity:
I/flutter ( 7958): TextAffinity.upstream, isDirectional: false)
I/flutter ( 7958): 
I/flutter ( 7958): When the exception was thrown, this was the stack:
I/flutter ( 7958): #0      TextEditingController.selection= (package:flutter/src/widgets/editable_text.dart:169:7)
I/flutter ( 7958): #1      EditableTextState._handleSelectionChanged (package:flutter/src/widgets/editable_text.dart:1216:23)
I/flutter ( 7958): #2      RenderEditable._handlePotentialSelectionChange (package:flutter/src/rendering/editable.dart:369:5)
I/flutter ( 7958): #3      RenderEditable.selectPositionAt (package:flutter/src/rendering/editable.dart:1416:9)
I/flutter ( 7958): #4      RenderEditable.selectPosition (package:flutter/src/rendering/editable.dart:1388:5)
I/flutter ( 7958): #5      _TextFieldState._handleSingleTapUp (package:flutter/src/material/text_field.dart:765:27)
I/flutter ( 7958): #6      _TextSelectionGestureDetectorState._handleTapUp (package:flutter/src/widgets/text_selection.dart:929:16)
I/flutter ( 7958): #7      TapGestureRecognizer._checkUp.<anonymous closure> (package:flutter/src/gestures/tap.dart:363:49)
I/flutter ( 7958): #8      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
I/flutter ( 7958): #9      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:363:11)
I/flutter ( 7958): #10     TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:312:7)
I/flutter ( 7958): #11     _TransparentTapGestureRecognizer.rejectGesture (package:flutter/src/widgets/text_selection.dart:1131:7)
I/flutter ( 7958): #12     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:159:26)
I/flutter ( 7958): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:222:20)
I/flutter ( 7958): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
I/flutter ( 7958): #15     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
I/flutter ( 7958): #16     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
I/flutter ( 7958): #17     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
I/flutter ( 7958): #21     _invoke1 (dart:ui/hooks.dart:250:10)
I/flutter ( 7958): #22     _dispatchPointerDataPacket (dart:ui/hooks.dart:159:5)
I/flutter ( 7958): (elided 3 frames from package dart:async)
I/flutter ( 7958): 
I/flutter ( 7958): Handler: "onTapUp"
I/flutter ( 7958): Recognizer:
I/flutter ( 7958):   _TransparentTapGestureRecognizer#0db7e
I/flutter ( 7958): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by jifalops** [comment]
Can you try this again using v0.3.0?

**Comment by jifalops** [comment]
The form bugs have been hopefully worked out in version [1.0.0-pre.1](https://pub.dev/packages/datetime_picker_formfield/versions/1.0.0-pre.1)
